/**
 * AppStrings.ts
 * Central build-time strings config.
 * When EXPO_PUBLIC_APP_MODE=android, all user-facing text uses neutral
 * scheduling/appointment language. Otherwise, original language is preserved.
 */

const isAndroidBuild = process.env.EXPO_PUBLIC_APP_MODE === 'android';

// --- Branding ---
export const APP_NAME = isAndroidBuild ? 'RAAJ Connect' : 'RAAJ MedHub';
export const APP_NAME_FULL = isAndroidBuild ? 'RAAJ Connect' : 'RAAJ MEDHUB';
export const APP_NAME_PROFESSIONAL = isAndroidBuild ? 'RAAJ Connect Professional' : 'RAAJ MEDHUB PROFESSIONAL';
export const APP_SUBTITLE = isAndroidBuild ? 'Smart Appointment Scheduling' : 'Professional Healthcare Management';
export const APP_VERSION_LABEL = isAndroidBuild ? `${APP_NAME} v1.0` : 'Raaj Medhub v1.0';

// --- Person Labels ---
export const PATIENT_LABEL = isAndroidBuild ? 'Client' : 'Patient';
export const PATIENT_LABEL_PLURAL = isAndroidBuild ? 'Clients' : 'Patients';
export const DOCTOR_LABEL = isAndroidBuild ? 'Specialist' : 'Doctor';
export const DOCTOR_LABEL_PLURAL = isAndroidBuild ? 'Specialists' : 'Doctors';
export const DR_PREFIX = isAndroidBuild ? '' : 'Dr. ';

// --- Navigation Labels ---
export const NAV_MY_PATIENTS = isAndroidBuild ? 'My Clients' : 'My Patients';
export const NAV_PATIENT_LIST = isAndroidBuild ? 'Client List' : 'Patient List';
export const NAV_PATIENT_REPORTS = isAndroidBuild ? 'Client Reports' : 'Patient Reports';
export const NAV_MY_REPORTS = isAndroidBuild ? 'My Documents' : 'My Reports';

// --- Content Labels ---
export const REFERRAL_LABEL = isAndroidBuild ? 'Booking Reference' : 'Referral';
export const REFERRAL_DOCUMENT = isAndroidBuild ? 'Upload Document' : 'Upload Referral';
export const CLINICAL_NOTES = isAndroidBuild ? 'Service Notes' : 'Clinical Notes';
export const PATIENT_INFO = isAndroidBuild ? 'Client Info' : 'Patient Info';
export const SERVICE_TYPE = isAndroidBuild ? 'Service Type' : 'Examination Type';
export const SPECIALIST_TYPE = isAndroidBuild ? 'Specialist credentials and bio' : 'Clinical credentials and bio';

// --- Security/Settings ---
export const SECURITY_DESCRIPTION = isAndroidBuild
  ? 'Regularly updating your password helps protect client data and your professional profile.'
  : 'Regularly updating your password helps protect patient data and your professional profile.';

// --- Location ---
export const DEFAULT_LOCATION = isAndroidBuild ? 'RAAJ Connect Centre' : 'RAAJ MEDHUB Clinic';
export const CONTACT_LOCATION = isAndroidBuild ? 'Contact location for pricing' : 'Contact clinic for pricing';

// --- Appointments screen ---
export const APPOINTMENTS_COMING_SOON = isAndroidBuild;
export const APPOINTMENTS_COMING_SOON_TITLE = 'Scheduling Coming Soon';
export const APPOINTMENTS_COMING_SOON_BODY =
  'Online booking will be available shortly. Please contact your nearest location directly to schedule an appointment.';

// --- Export / Data ---
export const EXPORT_BRAND_LABEL = isAndroidBuild ? APP_NAME_FULL : 'RAAJ MEDHUB';
export const EXPORT_FOOTER = isAndroidBuild
  ? `This is an official data export generated by the ${APP_NAME} mobile application.\nFor verification or inquiries, contact support at raajmedhub@gmail.com`
  : `This is an official data export generated by the Raaj Medhub mobile application.\nFor verification or inquiries, contact support at raajmedhub@gmail.com`;
export const EXPORT_FILE_PREFIX = isAndroidBuild ? 'RAAJ_Connect_Export' : 'Raaj_Medhub_Report';

// --- Dashboard fallback name ---
export const DASHBOARD_FALLBACK_NAME = isAndroidBuild ? 'User' : 'Patient';
