/**
 * AppStrings.ts
 * Central build-time strings config.
 * When EXPO_PUBLIC_APP_MODE=android, all user-facing text uses neutral
 * scheduling/appointment language. Otherwise, original language is preserved.
 */

import { Platform } from 'react-native';

export const isAndroidBuild = false;

// --- Branding ---
export const APP_NAME = 'RAAJ Connect';
export const APP_NAME_FULL = 'RAAJ CONNECT';
export const APP_NAME_PROFESSIONAL = 'RAAJ CONNECT PROFESSIONAL';
export const APP_SUBTITLE = 'Professional Healthcare Management';
export const APP_VERSION_LABEL = 'RAAJ Connect v1.0';

// --- Person Labels ---
export const PATIENT_LABEL = isAndroidBuild ? 'Customer' : 'Patient';
export const PATIENT_LABEL_PLURAL = isAndroidBuild ? 'Customers' : 'Patients';
export const DOCTOR_LABEL = isAndroidBuild ? 'Specialist' : 'Doctor';
export const DOCTOR_LABEL_PLURAL = isAndroidBuild ? 'Specialists' : 'Doctors';
export const DR_PREFIX = isAndroidBuild ? '' : 'Dr. ';

// --- Navigation Labels ---
export const NAV_MY_PATIENTS = isAndroidBuild ? 'My Clients' : 'My Patients';
export const NAV_PATIENT_LIST = isAndroidBuild ? 'Client List' : 'Patient List';
export const NAV_PATIENT_REPORTS = isAndroidBuild ? 'Client Reports' : 'Patient Reports';
export const NAV_MY_REPORTS = isAndroidBuild ? 'My Documents' : 'My Reports';

// --- Content Labels ---
export const REFERRAL_LABEL = isAndroidBuild ? 'Booking Reference' : 'Referral';
export const REFERRAL_DOCUMENT = isAndroidBuild ? 'Upload Document' : 'Upload Referral';
export const CLINICAL_NOTES = isAndroidBuild ? 'Service Notes' : 'Clinical Notes';
export const PATIENT_INFO = isAndroidBuild ? 'Client Info' : 'Patient Info';
export const SERVICE_TYPE = isAndroidBuild ? 'Service Type' : 'Examination Type';
export const SPECIALIST_TYPE = isAndroidBuild ? 'Specialist credentials and bio' : 'Clinical credentials and bio';

// --- Security/Settings ---
export const SECURITY_DESCRIPTION = isAndroidBuild
  ? 'Regularly updating your password helps protect client data and your professional profile.'
  : 'Regularly updating your password helps protect patient data and your professional profile.';

// --- Location ---
export const DEFAULT_LOCATION = isAndroidBuild ? 'RAAJ Connect Centre' : 'RAAJ MEDHUB Clinic';
export const CONTACT_LOCATION = isAndroidBuild ? 'Contact location for pricing' : 'Contact clinic for pricing';

// --- Appointments screen ---
export const APPOINTMENTS_COMING_SOON = isAndroidBuild;
export const APPOINTMENTS_COMING_SOON_TITLE = 'Scheduling Coming Soon';
export const APPOINTMENTS_COMING_SOON_BODY =
  'Online booking will be available shortly. Please contact your nearest location directly to schedule an appointment.';

// --- Export / Data ---
export const EXPORT_BRAND_LABEL = APP_NAME_FULL;
export const EXPORT_FOOTER = `This is an official data export generated by the ${APP_NAME} mobile application.\nFor verification or inquiries, contact support at raajmedhub@gmail.com`;
export const EXPORT_FILE_PREFIX = 'RAAJ_Connect_Export';

// --- Dashboard fallback name ---
export const DASHBOARD_FALLBACK_NAME = isAndroidBuild ? 'User' : 'Patient';

// --- Procedure & Clinical Term Replacements ---
export const PROC_CT_SCAN = isAndroidBuild ? 'Standard Service' : 'CT Scan';
export const PROC_XRAY = isAndroidBuild ? 'Basic Service' : 'X-Ray';
export const PROC_MRI = isAndroidBuild ? 'Advanced Service' : 'MRI';

export const MED_NOTES_LABEL = isAndroidBuild ? 'Session Notes' : 'Medical Notes';
export const MED_RECORD_LABEL = isAndroidBuild ? 'Session Record' : 'Medical Record';
export const DIAGNOSIS_LABEL = isAndroidBuild ? 'Primary Focus' : 'Diagnosis';
export const TREATMENT_LABEL = isAndroidBuild ? 'Action Plan' : 'Treatment Plan';
export const PRESCRIPTION_LABEL = isAndroidBuild ? 'Recommendations' : 'Prescription';
export const MEDICATION_LABEL = isAndroidBuild ? 'Current Items' : 'Current Medications';
export const ALLERGIES_LABEL = isAndroidBuild ? 'Restrictions' : 'Allergies';
export const CONDITIONS_LABEL = isAndroidBuild ? 'Special Conditions' : 'Medical Conditions';

// --- Informational Strings ---
export const PREGNANCY_WARNING = isAndroidBuild ? 'Inform your specialist of any special conditions.' : 'Tell your doctor if you are pregnant.';
export const SCANS_INFO = isAndroidBuild ? 'Any required services will appear here once processed.' : 'Any physical or imaging scans requested by your doctor will appear here once processed.';
export const HEALTH_TIPS = isAndroidBuild ? 'Alerts and service reminders' : 'Alerts, reminders, and health tips';
export const DOC_PROFESSIONAL_LABEL = isAndroidBuild ? 'CERTIFIED PROFESSIONAL' : 'MEDICAL PROFESSIONAL';
